FROM library/alpine:3.6
CMD /bin/sh -c "while true; do echo Hello, world; sleep 1; done"

LABEL org.label-schema.vendor="Fenago" \
  org.label-schema.url="http://fenago.com" \
  org.label-schema.name="Hello World" \
  org.label-schema.version="1.0.0" \
  org.label-schema.vcs-url="github.com:fenago/puppet-beginners-guide.git" \
  org.label-schema.docker.schema-version="1.0"
